version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - keycloak

  backend:
    build: ./backend
    volumes:
      - ./backend/src:/usr/src/app/src
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/misbah_edu
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=master
      - KEYCLOAK_CLIENT_ID=account
      - RABBITMQ_URL=amqp://rabbitmq
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
    depends_on:
      - mongo
      - keycloak
      - rabbitmq
      - minio

  video-processing-service:
    build: ./video-processing-service
    volumes:
      - ./video-processing-service/src:/usr/src/app/src
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://rabbitmq
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
      - MONGO_URI=mongodb://mongo:27017/misbah_edu
    depends_on:
      - rabbitmq
      - minio
      - mongo

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app
      # - /app/node_modules # Exclude node_modules from host mount
    environment:
      - VITE_KEYCLOAK_URL=http://localhost:80/auth
      - VITE_KEYCLOAK_REALM=master
      - VITE_KEYCLOAK_CLIENT_ID=frontend-client
      - VITE_BACKEND_URL=http://localhost:80/api
    depends_on:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - backend

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus

volumes:
  mongo-data:
  rabbitmq-data:
  minio-data:
  grafana-data:
