version: '3.8'
services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: edu-platform-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: edu-platform
    volumes:
      - mongo-data:/data/db



  # Backend API
  backend:
    build: ./backend
    container_name: edu-platform-backend
    restart: unless-stopped
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    volumes:
      - ./backend/src:/usr/src/app/src
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-5000}
      - MONGODB_URI=${MONGODB_URI:-mongodb://admin:password@mongo:27017/edu-platform?authSource=admin}
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=${MINIO_PORT:-9000}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin}
      - MINIO_USE_SSL=${MINIO_USE_SSL:-false}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME:-edu-platform}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3000}
    depends_on:
      - mongo
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    build: ./frontend
    container_name: edu-platform-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - .env
    environment:
      - VITE_BACKEND_URL=http://localhost:5000/api
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: edu-platform-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:latest
    container_name: edu-platform-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
  minio-data:
