version: '3.8'
services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: edu-platform-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: edu-platform
    volumes:
      - mongo-data:/data/db

  # Keycloak Authentication Server with PostgreSQL
  keycloak-db:
    image: postgres:15
    container_name: edu-platform-keycloak-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: edu-platform-keycloak
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    command: start-dev
    depends_on:
      - keycloak-db

  # Backend API
  backend:
    build: ./backend
    container_name: edu-platform-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/usr/src/app/src
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password@mongo:27017/edu-platform?authSource=admin
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=edu-platform
      - KEYCLOAK_CLIENT_ID=edu-platform-backend
      - KEYCLOAK_CLIENT_SECRET=your-client-secret
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - mongo
      - keycloak
      - minio

  # Frontend
  frontend:
    build: ./frontend
    container_name: edu-platform-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - VITE_KEYCLOAK_URL=http://localhost:8080
      - VITE_KEYCLOAK_REALM=edu-platform
      - VITE_KEYCLOAK_CLIENT_ID=edu-platform-frontend
      - VITE_BACKEND_URL=http://localhost:5000/api
    depends_on:
      - backend

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: edu-platform-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:latest
    container_name: edu-platform-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - keycloak

volumes:
  mongo-data:
  minio-data:
  keycloak-db-data:
